-- Transactional integration check. Rollback prevents pg_net email delivery.
begin;
do $$
declare employee uuid; hr uuid; it uuid; hr_ticket uuid; it_ticket uuid; n integer;
begin
 select id into employee from public.profiles where role='employee' limit 1;
 select id into hr from public.profiles where role='admin' limit 1;
 select id into it from public.profiles where role='super_admin' limit 1;
 if employee is null or hr is null or it is null then raise exception 'Test requires one profile per role'; end if;
 insert into public.employee_support_requests(user_id,category,subject,description) values(employee,'General HR Concern','Routing test','Synthetic rollback test') returning id into hr_ticket;
 insert into public.employee_support_requests(user_id,category,subject,description) values(employee,'IT Concern','Routing test','Synthetic rollback test') returning id into it_ticket;
 perform set_config('request.jwt.claim.sub',hr::text,true);
 set local role authenticated;
 select count(*) into n from public.employee_support_requests where id in (hr_ticket,it_ticket);
 if n <> 1 then raise exception 'HR must see exactly its HR ticket'; end if;
 update public.employee_support_requests set hr_notes='Blocked' where id=it_ticket;
 get diagnostics n = row_count;
 if n <> 0 then raise exception 'HR updated IT ticket'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub',it::text,true);
 set local role authenticated;
 select count(*) into n from public.employee_support_requests where id in (hr_ticket,it_ticket);
 if n <> 1 then raise exception 'IT must see exactly its IT ticket'; end if;
 update public.employee_support_requests set status='Resolved',hr_notes='Resolved by IT' where id=it_ticket;
 get diagnostics n = row_count;
 if n <> 1 then raise exception 'IT could not resolve its ticket'; end if;
 update public.employee_support_requests set status='Open' where id=it_ticket;
 get diagnostics n = row_count;
 if n <> 0 then raise exception 'Resolved ticket reopened'; end if;
 reset role;
 begin
  update public.employee_support_requests set hr_notes='Overwrite history' where id=it_ticket;
  raise exception 'History guard did not reject update';
 exception when check_violation then null;
 end;
 perform set_config('request.jwt.claim.sub',employee::text,true);
 set local role authenticated;
 select count(*) into n from public.employee_support_requests where id in (hr_ticket,it_ticket);
 if n <> 2 then raise exception 'Employee cannot see own history'; end if;
 begin
  update public.employee_support_requests set hr_notes='Forged reply' where id=hr_ticket;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'Employee forged reply'; end if;
 exception when check_violation or insufficient_privilege then null;
 end;
 begin
  update public.employee_support_requests set status='Cancelled',hr_notes='Forged cancellation reply' where id=hr_ticket;
  raise exception 'Employee altered reply while cancelling';
 exception when check_violation or insufficient_privilege then null;
 end;
 update public.employee_support_requests set status='Cancelled' where id=hr_ticket;
 get diagnostics n = row_count;
 if n <> 1 then raise exception 'Employee could not cancel own request'; end if;
 update public.employee_support_requests set status='Open' where id=hr_ticket;
 get diagnostics n = row_count;
 if n <> 0 then raise exception 'Employee reopened cancelled ticket'; end if;
 select count(*) into n from public.employee_support_requests where id=hr_ticket and status='Cancelled';
 if n <> 1 then raise exception 'Cancelled request missing from owner history'; end if;
 update public.employee_support_requests set status='Cancelled' where id=it_ticket;
 get diagnostics n = row_count;
 if n <> 0 then raise exception 'Employee cancelled resolved request'; end if;
 reset role;
 insert into public.employee_support_requests(user_id,category,subject,description) values(hr,'IT Concern','Other owner','Synthetic rollback test') returning id into hr_ticket;
 perform set_config('request.jwt.claim.sub',employee::text,true);
 set local role authenticated;
 update public.employee_support_requests set status='Cancelled' where id=hr_ticket;
 get diagnostics n = row_count;
 if n <> 0 then raise exception 'Employee cancelled another users ticket'; end if;
 reset role;
 insert into public.employee_support_requests(user_id,category,subject,description) values(employee,'General HR Concern','HR cancellation','Synthetic rollback test') returning id into hr_ticket;
 perform set_config('request.jwt.claim.sub',hr::text,true);
 set local role authenticated;
 update public.employee_support_requests set status='Cancelled',hr_notes='Cancelled by HR' where id=hr_ticket;
 get diagnostics n = row_count;
 if n <> 1 then raise exception 'HR could not cancel its ticket'; end if;
 update public.employee_support_requests set status='Open' where id=hr_ticket;
 get diagnostics n = row_count;
 if n <> 0 then raise exception 'HR reopened cancelled ticket'; end if;
 update public.employee_support_requests set status='Cancelled' where id=it_ticket;
 get diagnostics n = row_count;
 if n <> 0 then raise exception 'HR cancelled IT ticket'; end if;
 reset role;
end;
$$;
rollback;
