'use client';
import LanguageSetting from '@/components/language/LanguageSetting';
import { T, useLanguage } from '@/components/language/LanguageProvider';


import { useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { AlertTriangle, Bell, CalendarClock, CheckCircle2, ChevronLeft, ChevronRight, Gauge, Gift, Headphones, Plane, RotateCcw, Search, Settings, Shield, ShieldAlert, SlidersHorizontal } from 'lucide-react';
import Spinner from '@/components/Spinner';
import ModalShell from '@/components/shared/ModalShell';
import { APP_SETTING_CATEGORIES, APP_SETTING_DEFINITIONS, type AppSettingCategory, type AppSettingDefinition, type AppSettingsValues } from '@/lib/app-settings';
import { resolveSeasonalTheme, SEASONAL_THEME_PRESENTATION } from '@/lib/seasonal-theme';
import VerificationDialog, { type VerificationTone } from '@/components/shared/VerificationDialog';

type Props = { open: boolean; onClose: () => void; appSettings: AppSettingsValues; savedAppSettings: AppSettingsValues | null; appSettingsLoading: boolean; appSettingsMsg: { type: 'success' | 'error'; text: string } | null; appSettingsSaving: boolean; saveAppSettings: () => boolean | void | Promise<boolean | void>; setAppSettings: Dispatch<SetStateAction<AppSettingsValues>> };
const categories = Object.keys(APP_SETTING_CATEGORIES) as AppSettingCategory[];
const categoryMeta = {
  attendance: { icon: CalendarClock, description: 'Work hours, late rules, and attendance' }, leave: { icon: Plane, description: 'Leave rules and policies' }, services: { icon: Headphones, description: 'Support, documents, directory, etc.' }, notifications: { icon: Bell, description: 'Reminders and notification rules' }, features: { icon: SlidersHorizontal, description: 'Enable or disable application features' }, seasonal: { icon: Gift, description: 'Scheduled portal themes and holiday accents' }, system: { icon: Gauge, description: 'Performance and system behavior' }, security: { icon: Shield, description: 'Security, access, and maintenance' },
} satisfies Record<AppSettingCategory, { icon: typeof Settings; description: string }>;

function SettingControl({ definition, value, onChange }: { definition: AppSettingDefinition; value: string | number | boolean; onChange: (value: string | number | boolean) => void }) {
  if (definition.type === 'boolean') return <button type="button" role="switch" aria-checked={Boolean(value)} onClick={() => onChange(!value)} className={`relative h-7 w-12 flex-none rounded-full transition ${value ? 'bg-green-600' : 'bg-slate-300 dark:bg-slate-600'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${value ? 'start-6' : 'start-1'}`}/><span className="sr-only"><T>{value ? 'Enabled' : 'Disabled'}</T></span></button>;
  if (definition.type === 'string') return <textarea value={String(value)} onChange={(event) => onChange(event.target.value)} rows={3} className="input-field mt-3 resize-none text-xs"/>;
  if (definition.type === 'select') return <select value={String(value)} onChange={(event) => onChange(event.target.value)} className="input-field mt-3 !min-h-11 text-xs">{definition.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>;
  if (definition.type === 'date') return <input type="date" value={String(value)} onChange={(event) => onChange(event.target.value)} className="input-field mt-3 !min-h-11 text-xs"/>;
  return <div className="mt-3 flex items-center gap-2"><input type="number" min={definition.min} max={definition.max} step={definition.step || 1} value={Number(value)} onChange={(event) => onChange(Math.min(definition.max ?? Infinity, Math.max(definition.min ?? -Infinity, Number(event.target.value))))} className="input-field !min-h-11 flex-1 !py-2 text-sm"/><span className="min-w-14 text-end text-[10px] font-semibold text-slate-500 dark:!text-[#aab8ad]">{definition.unit}</span></div>;
}

export default function AppSettingsModal({ open, onClose, appSettings, savedAppSettings, appSettingsLoading, appSettingsMsg, appSettingsSaving, saveAppSettings, setAppSettings }: Props) {
  const { t: localize } = useLanguage();
  const [category, setCategory] = useState<AppSettingCategory | null>(null);
  const [query, setQuery] = useState('');
  const [verification, setVerification] = useState<null | { title: string; description: string; confirmLabel: string; tone: VerificationTone; details: string[]; action: () => void | Promise<void> }>(null);
  const dirty = savedAppSettings !== null && JSON.stringify(appSettings) !== JSON.stringify(savedAppSettings);
  const changedCount = savedAppSettings ? Object.keys(appSettings).filter((key) => appSettings[key] !== savedAppSettings[key]).length : 0;
  const visibleDefinitions = useMemo(() => { const normalized = query.trim().toLowerCase(); return APP_SETTING_DEFINITIONS.filter((item) => normalized ? `${item.label} ${item.description} ${APP_SETTING_CATEGORIES[item.category]}`.toLowerCase().includes(normalized) : item.category === category); }, [category, query]);
  const requestClose = () => {
    if (!dirty) return onClose();
    setVerification({ title: 'Discard unsaved changes?', description: 'Your settings will return to the last saved version.', confirmLabel: 'Discard changes', tone: 'warning', details: [`${changedCount} unsaved change${changedCount === 1 ? '' : 's'} will be removed.`], action: () => { setVerification(null); onClose(); } });
  };
  const resetCategory = () => {
    if (!category) return;
    const definitions = APP_SETTING_DEFINITIONS.filter((item) => item.category === category);
    const changes = definitions.filter((item) => appSettings[item.key] !== item.defaultValue).map((item) => `${item.label}: ${String(appSettings[item.key])} → ${String(item.defaultValue)}`);
    if (!changes.length) return;
    setVerification({ title: `Reset ${APP_SETTING_CATEGORIES[category]}?`, description: 'Review the defaults below. They remain unsaved until you select Review & Save.', confirmLabel: 'Apply defaults', tone: 'warning', details: changes, action: () => { setAppSettings((current) => ({ ...current, ...Object.fromEntries(definitions.map((item) => [item.key, item.defaultValue])) })); setVerification(null); } });
  };
  const updateSetting = (definition: AppSettingDefinition, value: string | number | boolean) => {
    const apply = () => { setAppSettings((current) => ({ ...current, [definition.key]: value })); setVerification(null); };
    if (definition.dangerous && value !== definition.defaultValue) return setVerification({ title: `Verify ${definition.label}`, description: 'This is a sensitive global control and may immediately affect employee access or records.', confirmLabel: 'Apply change', tone: 'danger', details: [`New value: ${String(value)}`, definition.description], action: apply });
    apply();
  };
  const reviewAndSave = () => {
    if (!savedAppSettings) return;
    const changes = APP_SETTING_DEFINITIONS.filter((item) => savedAppSettings[item.key] !== appSettings[item.key]).map((item) => `${item.label}: ${String(savedAppSettings[item.key])} → ${String(appSettings[item.key])}`);
    if (!changes.length) return;
    setVerification({ title: 'Confirm global settings', description: 'These changes affect the live application after saving. Review each value before continuing.', confirmLabel: `Save ${changes.length} change${changes.length === 1 ? '' : 's'}`, tone: 'primary', details: changes, action: async () => { const saved = await saveAppSettings(); if (saved !== false) setVerification(null); } });
  };
  const showOverview = !category && !query;
  const seasonalPreview = resolveSeasonalTheme(appSettings, 'employee');
  const seasonalPresentation = SEASONAL_THEME_PRESENTATION[seasonalPreview.variant];
  const footer = appSettingsLoading ? undefined : showOverview ? <button type="button" onClick={() => setCategory('attendance')} className="btn-primary min-h-11 w-full"><T>{"Manage App Settings "}</T><ChevronRight size={16}/></button> : <div className="flex items-center justify-between gap-3"><div><p className={`text-xs font-bold ${dirty ? 'text-orange-700 dark:text-orange-300' : 'text-slate-500 dark:!text-[#aab8ad]'}`}><T>{dirty ? `${changedCount} unsaved change${changedCount === 1 ? '' : 's'}` : 'All changes saved'}</T></p>{dirty ? <button type="button" onClick={requestClose} className="mt-1 text-[10px] font-bold text-slate-600 underline dark:!text-[#e3ece4]"><T>{"Discard changes"}</T></button> : null}</div><button type="button" onClick={reviewAndSave} disabled={appSettingsSaving || !dirty} className="btn-primary min-h-11 px-4 disabled:opacity-50"><T>{appSettingsSaving ? <span className="flex items-center gap-2"><Spinner size="sm"/><T>{"Saving…"}</T></span> : 'Review & Save'}</T></button></div>;

  return <ModalShell open={open} onClose={requestClose} title={localize("App Settings")} description={localize("Configure global application settings")} icon={<Settings size={20}/>} size="sm" placement="right" closeDisabled={appSettingsSaving} footer={footer}>
    <div className="relative mb-4"><Search size={15} className="pointer-events-none absolute start-3 top-1/2 -translate-y-1/2 text-slate-400"/><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={localize("Search settings…")} className="input-field !min-h-11 !ps-9 text-xs"/></div>
	    <LanguageSetting />
    {appSettingsMsg ? <div role="status" className={`mb-4 rounded-xl border p-3 text-xs font-bold ${appSettingsMsg.type === 'success' ? 'border-green-200 bg-green-50 text-green-800 dark:border-green-800 dark:bg-green-950/50 dark:!text-white' : 'border-red-200 bg-red-50 text-red-800 dark:border-red-800 dark:bg-red-950/50 dark:!text-white'}`}>{appSettingsMsg.text}</div> : null}
	    {category === 'seasonal' && !query ? <div className={`mb-4 rounded-2xl bg-gradient-to-br p-4 text-white ${seasonalPresentation.bannerTone}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-black uppercase tracking-wider">{seasonalPresentation.label}<T>{" preview"}</T></span><span className={`rounded-full px-2 py-1 text-[9px] font-black ${seasonalPreview.status === 'active' ? 'bg-green-400 text-green-950' : seasonalPreview.status === 'scheduled' ? 'bg-amber-300 text-amber-950' : 'bg-white/15 text-white'}`}>{seasonalPreview.status.toUpperCase()}</span></div><p className="mt-2 text-[10px] text-white/75"><T>{seasonalPreview.scope === 'employee_and_hr' ? 'Employee and HR portals' : 'Employee portal'}</T> · {seasonalPreview.intensity}<T>{" intensity"}</T></p><p className="mt-1 text-[9px] text-white/60"><T>{"This visual layer preserves portal workflows and warning states."}</T></p></div> : null}
    {appSettingsLoading ? <div className="py-12 text-center text-sm text-slate-500 dark:!text-[#aab8ad]"><T>{"Loading settings…"}</T></div> : showOverview ? <>
      <div className="space-y-2.5">{categories.map((key) => { const meta = categoryMeta[key]; const Icon = meta.icon; const count = APP_SETTING_DEFINITIONS.filter((item) => item.category === key).length; return <button key={key} type="button" onClick={() => setCategory(key)} className="flex min-h-20 w-full items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-start transition hover:border-green-300 hover:bg-green-50/40 dark:border-slate-700 dark:bg-[#202521] dark:hover:border-green-800"><span className="grid h-10 w-10 flex-none place-items-center rounded-xl bg-green-50 text-green-700 dark:bg-green-950/50 dark:text-green-300"><Icon size={18}/></span><span className="min-w-0 flex-1"><span className="block text-xs font-bold text-slate-950 dark:text-white">{APP_SETTING_CATEGORIES[key]}</span><span className="mt-1 block truncate text-[10px] text-slate-500 dark:!text-[#aab8ad]">{meta.description}</span></span><span className="grid h-6 min-w-6 place-items-center rounded-full bg-slate-200 px-1.5 text-[9px] font-black text-slate-700 dark:bg-slate-700 dark:!text-white">{count}</span></button>; })}</div>
      <section className="mt-5 rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><p className="text-[10px] font-black text-slate-800 dark:!text-white"><T>{"Settings Status Legend"}</T></p><div className="mt-3 space-y-3"><div className="flex gap-2"><span className="mt-1 h-2 w-2 rounded-full bg-green-500"/><span><span className="block text-[10px] font-bold text-slate-800 dark:!text-white"><T>{"Active"}</T></span><span className="text-[9px] text-slate-500 dark:!text-[#aab8ad]"><T>{"Currently affecting the application"}</T></span></span></div><div className="flex gap-2"><span className="mt-1 h-2 w-2 rounded-full bg-orange-500"/><span><span className="block text-[10px] font-bold text-slate-800 dark:!text-white"><T>{"Future Control"}</T></span><span className="text-[9px] text-slate-500 dark:!text-[#aab8ad]"><T>{"Saved for future use / not yet active"}</T></span></span></div></div></section>
    </> : <section><div className="mb-4 flex items-start justify-between gap-2"><button type="button" onClick={() => { setCategory(null); setQuery(''); }} className="inline-flex min-h-11 items-center gap-1 text-[10px] font-bold text-slate-600 dark:!text-[#e3ece4]"><ChevronLeft size={15}/><T>{"Categories"}</T></button>{category && !query ? <button type="button" onClick={resetCategory} className="inline-flex min-h-11 items-center gap-1 text-[10px] font-bold text-slate-600 dark:!text-[#e3ece4]"><RotateCcw size={14}/><T>{"Reset"}</T></button> : null}</div><h3 className="mb-1 text-base font-black text-slate-950 dark:text-white"><T>{query ? 'Search Results' : category ? APP_SETTING_CATEGORIES[category] : 'Settings'}</T></h3><p className="mb-4 text-[10px] text-slate-500 dark:!text-[#aab8ad]"><T>{"ACTIVE controls are enforced now. FUTURE CONTROL values are stored only."}</T></p><div className="space-y-3">{visibleDefinitions.map((item) => <article key={item.key} className={`rounded-2xl border p-3 ${item.dangerous ? 'border-orange-200 bg-orange-50/50 dark:border-orange-800 dark:bg-orange-950/20' : 'border-slate-200 bg-slate-50 dark:border-slate-700 dark:bg-[#202521]'}`}><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="text-xs font-bold text-slate-950 dark:text-white"><T>{item.label}</T></h4><span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[8px] font-black ${item.status === 'active' ? 'bg-green-100 text-green-800 dark:bg-green-950 dark:!text-white' : 'bg-orange-100 text-orange-800 dark:bg-orange-950 dark:text-orange-200'}`}>{item.status === 'active' ? <CheckCircle2 size={9}/> : <AlertTriangle size={9}/>} <T>{item.status === 'active' ? 'ACTIVE' : 'FUTURE'}</T></span>{item.dangerous ? <ShieldAlert size={14} className="text-orange-600"/> : null}</div><p className="mt-1 text-[10px] leading-relaxed text-slate-600 dark:!text-[#c3d0c5]">{item.description}</p></div>{item.type === 'boolean' ? <SettingControl definition={item} value={appSettings[item.key]} onChange={(value) => updateSetting(item, value)}/> : null}</div>{item.type !== 'boolean' ? <SettingControl definition={item} value={appSettings[item.key]} onChange={(value) => updateSetting(item, value)}/> : null}</article>)}{visibleDefinitions.length === 0 ? <p className="py-10 text-center text-xs text-slate-500"><T>{"No matching settings."}</T></p> : null}</div></section>}
    <VerificationDialog open={Boolean(verification)} title={verification?.title ?? ''} description={verification?.description ?? ''} confirmLabel={verification?.confirmLabel ?? 'Confirm'} tone={verification?.tone} details={verification?.details} busy={appSettingsSaving} onCancel={() => { if (!appSettingsSaving) setVerification(null); }} onConfirm={() => verification?.action()} />
  </ModalShell>;
}
