'use client';

import EmptyState from '@/components/shared/EmptyState';
import ModalShell from '@/components/shared/ModalShell';

type Props = { open: boolean; onClose: () => void; loading: boolean; logs: any[]; allCount: number; pageSize: number; page: number; totalPages: number; onPageChange: (updater: (page: number) => number) => void; actionMeta: (action: string) => { icon: string; label: string } };

export default function AuditLogModal({ open, onClose, loading, logs, allCount, pageSize, page, totalPages, onPageChange, actionMeta }: Props) {
  return <ModalShell open={open} onClose={onClose} title="Audit Log" description="Admin and system actions, most recent first" icon="🧭" size="md">
    <div className="space-y-2">{loading && Array.from({ length: 5 }).map((_, index) => <div key={index} className="animate-pulse rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800"><div className="mb-2 h-3 w-2/3 rounded bg-slate-200 dark:bg-slate-700"/><div className="h-2.5 w-1/3 rounded bg-slate-200 dark:bg-slate-700"/></div>)}{!loading && logs.map((log) => { const meta = actionMeta(log.action); return <article key={log.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800"><div className="flex items-start gap-3"><span className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-white text-base dark:border-slate-700 dark:bg-slate-900">{meta.icon}</span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold text-slate-950 dark:text-white">{meta.label}</p><p className="mt-1 text-xs text-slate-600 dark:text-slate-300">{log.summary}</p><p className="mt-1 text-[10px] text-slate-500 dark:text-slate-400">{log.actor_name ?? 'Unknown'} · {new Date(log.created_at).toLocaleString('en-US', { timeZone: 'Asia/Riyadh', month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p></div></div></article>; })}{!loading && allCount === 0 && <EmptyState icon="🧭" title="No audit entries yet" description="Tracked administrative actions will appear here." />}</div>
    {allCount > pageSize && <nav className="mt-4 flex items-center justify-between" aria-label="Audit log pagination"><button type="button" onClick={() => onPageChange((value) => Math.max(1, value - 1))} disabled={page === 1} className="min-h-11 rounded-full px-3 text-xs font-bold text-blue-600 disabled:text-slate-300 dark:text-blue-300 dark:disabled:text-slate-600">← Previous</button><span className="text-[10px] font-medium text-slate-500 dark:text-slate-300">Page {page} of {totalPages}</span><button type="button" onClick={() => onPageChange((value) => Math.min(totalPages, value + 1))} disabled={page === totalPages} className="min-h-11 rounded-full px-3 text-xs font-bold text-blue-600 disabled:text-slate-300 dark:text-blue-300 dark:disabled:text-slate-600">Next →</button></nav>}
  </ModalShell>;
}
