'use client';
import { T, useLanguage } from '@/components/language/LanguageProvider';


import { LoadingRow } from '@/components/Spinner';
import EmptyState from '@/components/shared/EmptyState';
import ModalShell from '@/components/shared/ModalShell';
import type { RefObject } from 'react';

type Props = { open: boolean; onClose: () => void; saving: boolean; loading: boolean; title: string; setTitle: (value: string) => void; category: string; setCategory: (value: string) => void; file: File | null; setFile: (file: File | null) => void; fileRef: RefObject<HTMLInputElement | null>; documents: any[]; onUpload: () => void; onToggle: (document: any) => void; onDelete: (document: any) => void };

export default function EmployeeDocumentsModal({ open, onClose, saving, loading, title, setTitle, category, setCategory, file, setFile, fileRef, documents, onUpload, onToggle, onDelete }: Props) {
  const { t: localize } = useLanguage();
  return <ModalShell open={open} onClose={onClose} closeDisabled={saving} title={localize("Employee Documents")} description={localize("Publish policies, memorandums, handbooks, and forms to employees")} icon="📚" size="lg">
    <section className="mb-5 rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800"><p className="label-branded mb-3"><T>{"Publish new document"}</T></p><div className="grid grid-cols-1 gap-2 sm:grid-cols-2"><input className="input-field min-h-11 !py-2 !text-xs" value={title} onChange={(event) => setTitle(event.target.value)} placeholder={localize("Document title")}/><select className="input-field min-h-11 !py-2 !text-xs" value={category} onChange={(event) => setCategory(event.target.value)}><option value="Employee Handbook"><T>{"Employee Handbook"}</T></option><option value="Company Policy"><T>{"Company Policy"}</T></option><option value="Memorandum"><T>{"Memorandum"}</T></option><option value="Form"><T>{"Form"}</T></option><option value="Other"><T>{"Other"}</T></option></select></div><input ref={fileRef} type="file" className="input-field mt-2 min-h-11 !py-2 !text-xs" onChange={(event) => setFile(event.target.files?.[0] || null)}/><button type="button" onClick={onUpload} disabled={saving || !title.trim() || !file} className="btn-primary mt-3 min-h-11 w-full disabled:opacity-50"><T>{saving ? 'Publishing...' : 'Publish to employees'}</T></button></section>
    {loading ? <LoadingRow label={localize("Loading documents...")} /> : documents.length === 0 ? <EmptyState icon="📚" title={localize("No employee documents published yet")} /> : <div className="space-y-2">{documents.map((document) => <article key={document.id} className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="truncate text-xs font-extrabold text-slate-950 dark:text-white">{document.title}</p><p className="truncate text-[10px] text-slate-500 dark:text-slate-300">{document.category} · {document.file_name}</p><span className={`mt-1 inline-block text-[9px] font-bold uppercase ${document.is_active ? 'text-emerald-600 dark:text-emerald-300' : 'text-slate-500 dark:text-slate-400'}`}><T>{document.is_active ? 'Published' : 'Hidden'}</T></span></div><div className="flex flex-shrink-0 gap-2"><button type="button" onClick={() => onToggle(document)} className="min-h-11 rounded-full px-3 text-[10px] font-bold text-blue-600 hover:bg-blue-50 dark:text-blue-300 dark:hover:bg-blue-950/40"><T>{document.is_active ? 'Hide' : 'Publish'}</T></button><button type="button" onClick={() => onDelete(document)} className="min-h-11 rounded-full px-3 text-[10px] font-bold text-rose-600 hover:bg-rose-50 dark:text-rose-300 dark:hover:bg-rose-950/40"><T>{"Delete"}</T></button></div></article>)}</div>}
  </ModalShell>;
}
